name: Deployment Workflow Build and Push

on:
  workflow_dispatch: 
  push:
    branches: [main, dev-abgabe]    
    tags:
      - 'v*.*'              

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: conduit-backend
  IMAGE_FRONTEND: conduit-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_BACKEND }}
          file: ${{ env.IMAGE_BACKEND }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_BACKEND }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_BACKEND }}:${{ github.ref_name }}

      # Build and push frontend image
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.IMAGE_FRONTEND }}
          file: ${{ env.IMAGE_FRONTEND }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_FRONTEND }}:${{ github.ref_name }}
