# .github/workflows/pr-test.yml
name: PR Test Workflow

# Trigger this workflow when a pull request targets the dev-abgabe branch
on:
  pull_request:
    branches: [main]

jobs:
  # Job 1: Run backend tests using Python 3.5 inside a Docker container
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository including submodules (frontend and backend)
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Step 2: Run backend tests inside a Python 3.5 Docker container
      - name: Run backend tests in Python 3.5 container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app/backend \
            python:3.5 \
            bash -c "pip install -r requirements.txt && pytest"

  # Job 2: Run frontend tests using Node.js 20
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository including submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Step 2: Set up Node.js 20 for Angular frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install frontend dependencies and run Angular tests
      - name: Install frontend dependencies and run tests
        run: |
          cd frontend
          npm install
          npm run test
